export type Country = {
  slug: string;
  name: string;
  code: string;
  region: string;
  population: string;
  ecommerceRevenue: string;
  ecommerceGrowth: string;
  topPlatforms: string[];
  paymentMethods: string[];
  shippingConsiderations: string;
  consumerBehavior: string;
  topNiches: string[];
  challenges: string[];
  opportunities: string[];
  vatTax: string;
  currency: string;
  language: string;
  tier: "S" | "A" | "B" | "C";
};

export const countries: Country[] = [
  {
    slug: "united-states",
    name: "United States",
    code: "US",
    region: "North America",
    population: "335 million",
    ecommerceRevenue: "$1.2 trillion",
    ecommerceGrowth: "8.4%",
    topPlatforms: ["Shopify", "Amazon", "WooCommerce", "BigCommerce"],
    paymentMethods: ["Credit Cards", "PayPal", "Shop Pay", "Apple Pay", "Buy Now Pay Later"],
    shippingConsiderations: "2-5 day shipping expected. Free shipping over $50 standard. Multiple carrier options.",
    consumerBehavior: "High expectations for fast shipping and easy returns. Mobile commerce growing rapidly. Social commerce adoption increasing.",
    topNiches: ["Health & wellness", "Pet products", "Home office", "Sustainable products", "Tech accessories"],
    challenges: ["High competition", "Rising ad costs", "Return expectations", "Sales tax complexity"],
    opportunities: ["Largest ecommerce market", "High purchasing power", "TikTok Shop growth", "Subscription models"],
    vatTax: "Sales tax varies by state (0-10.25%)",
    currency: "USD",
    language: "English",
    tier: "S"
  },
  {
    slug: "united-kingdom",
    name: "United Kingdom",
    code: "GB",
    region: "Europe",
    population: "67 million",
    ecommerceRevenue: "$180 billion",
    ecommerceGrowth: "6.2%",
    topPlatforms: ["Amazon UK", "Shopify", "eBay UK", "WooCommerce"],
    paymentMethods: ["Debit Cards", "Credit Cards", "PayPal", "Klarna", "Apple Pay"],
    shippingConsiderations: "Next-day delivery common. Royal Mail and courier services. Post-Brexit customs for EU goods.",
    consumerBehavior: "Price-conscious but quality-focused. High mobile adoption. Strong social media influence on purchases.",
    topNiches: ["Fashion", "Beauty", "Home & garden", "Electronics", "Pet supplies"],
    challenges: ["Brexit import duties", "High competition", "Weather affecting seasonal products"],
    opportunities: ["English-speaking market", "High ecommerce penetration", "Strong social commerce"],
    vatTax: "20% VAT",
    currency: "GBP",
    language: "English",
    tier: "S"
  },
  {
    slug: "germany",
    name: "Germany",
    code: "DE",
    region: "Europe",
    population: "84 million",
    ecommerceRevenue: "$142 billion",
    ecommerceGrowth: "5.8%",
    topPlatforms: ["Amazon.de", "Otto", "Zalando", "eBay.de", "Shopify"],
    paymentMethods: ["PayPal", "Invoice (Rechnung)", "Direct Debit", "Credit Cards", "Klarna"],
    shippingConsiderations: "Fast delivery expected. DHL dominant. Free returns legally required within 14 days.",
    consumerBehavior: "Quality-focused, research-heavy buyers. Strong preference for invoice payment. Environmental consciousness.",
    topNiches: ["Electronics", "Fashion", "Home improvement", "Outdoor", "Sustainable products"],
    challenges: ["Language barrier", "Strict consumer protection laws", "Invoice payment complexity"],
    opportunities: ["Largest EU market", "High purchasing power", "Growing sustainability focus"],
    vatTax: "19% VAT",
    currency: "EUR",
    language: "German",
    tier: "S"
  },
  {
    slug: "australia",
    name: "Australia",
    code: "AU",
    region: "Oceania",
    population: "26 million",
    ecommerceRevenue: "$56 billion",
    ecommerceGrowth: "12.3%",
    topPlatforms: ["Amazon AU", "eBay AU", "Shopify", "Kogan"],
    paymentMethods: ["Credit Cards", "PayPal", "Afterpay", "Zip Pay", "Apple Pay"],
    shippingConsiderations: "Remote shipping challenges. Australia Post primary carrier. Longer international shipping times.",
    consumerBehavior: "Early BNPL adopters. Outdoor lifestyle focus. Willing to pay for quality.",
    topNiches: ["Outdoor & camping", "Fitness", "Pet products", "Home & garden", "Beauty"],
    challenges: ["Small population", "Shipping times from overseas", "Geographic isolation"],
    opportunities: ["High disposable income", "BNPL popularity", "Growing ecommerce adoption"],
    vatTax: "10% GST",
    currency: "AUD",
    language: "English",
    tier: "A"
  },
  {
    slug: "canada",
    name: "Canada",
    code: "CA",
    region: "North America",
    population: "40 million",
    ecommerceRevenue: "$75 billion",
    ecommerceGrowth: "9.1%",
    topPlatforms: ["Amazon.ca", "Shopify", "Walmart Canada", "eBay Canada"],
    paymentMethods: ["Credit Cards", "PayPal", "Interac", "Apple Pay", "Afterpay"],
    shippingConsiderations: "US suppliers ship easily. Canada Post and UPS common. Remote areas expensive.",
    consumerBehavior: "Similar to US but more price-sensitive. Bilingual market (English/French). Quality-conscious.",
    topNiches: ["Outdoor gear", "Winter products", "Home office", "Health & wellness", "Pet supplies"],
    challenges: ["Smaller market than US", "French Quebec market", "Remote shipping costs"],
    opportunities: ["Easy expansion from US", "High ecommerce growth", "Less competition than US"],
    vatTax: "5% GST + Provincial taxes (varies)",
    currency: "CAD",
    language: "English, French",
    tier: "A"
  },
  {
    slug: "france",
    name: "France",
    code: "FR",
    region: "Europe",
    population: "68 million",
    ecommerceRevenue: "$90 billion",
    ecommerceGrowth: "7.2%",
    topPlatforms: ["Amazon.fr", "Cdiscount", "Fnac", "Shopify", "Veepee"],
    paymentMethods: ["Carte Bancaire", "PayPal", "Credit Cards", "Apple Pay", "Alma"],
    shippingConsiderations: "La Poste and Colissimo. Relay point delivery popular. Free returns expected.",
    consumerBehavior: "Brand-conscious. Quality over price. Strong fashion and beauty interest.",
    topNiches: ["Fashion", "Beauty", "Luxury goods", "Home decor", "Gourmet food"],
    challenges: ["French language required", "Strong local competition", "Consumer protection laws"],
    opportunities: ["Large market", "Fashion-forward consumers", "Growing social commerce"],
    vatTax: "20% VAT",
    currency: "EUR",
    language: "French",
    tier: "A"
  },
  {
    slug: "netherlands",
    name: "Netherlands",
    code: "NL",
    region: "Europe",
    population: "18 million",
    ecommerceRevenue: "$35 billion",
    ecommerceGrowth: "8.5%",
    topPlatforms: ["Bol.com", "Amazon.nl", "Coolblue", "Shopify"],
    paymentMethods: ["iDEAL", "Credit Cards", "PayPal", "Klarna", "Bancontact"],
    shippingConsiderations: "PostNL dominant. Fast delivery standard. Easy Belgium cross-border.",
    consumerBehavior: "High English proficiency. Tech-savvy. Value convenience and speed.",
    topNiches: ["Electronics", "Fashion", "Home & living", "Sports", "Cycling gear"],
    challenges: ["iDEAL payment required", "Small market", "Local platform dominance"],
    opportunities: ["High ecommerce penetration", "English-friendly", "Gateway to EU"],
    vatTax: "21% VAT",
    currency: "EUR",
    language: "Dutch, English widely spoken",
    tier: "A"
  },
  {
    slug: "spain",
    name: "Spain",
    code: "ES",
    region: "Europe",
    population: "48 million",
    ecommerceRevenue: "$48 billion",
    ecommerceGrowth: "10.2%",
    topPlatforms: ["Amazon.es", "El Corte Inglés", "AliExpress", "Shopify"],
    paymentMethods: ["Credit Cards", "PayPal", "Bizum", "Cash on Delivery"],
    shippingConsiderations: "Correos and SEUR common. Cash on delivery still used. Island shipping complex.",
    consumerBehavior: "Price-sensitive. Mobile-first shopping. Growing online trust.",
    topNiches: ["Fashion", "Electronics", "Home goods", "Sports", "Beauty"],
    challenges: ["Price sensitivity", "Cash on delivery risk", "Regional variations"],
    opportunities: ["Growing market", "High smartphone usage", "Younger demographic online"],
    vatTax: "21% VAT",
    currency: "EUR",
    language: "Spanish",
    tier: "A"
  },
  {
    slug: "italy",
    name: "Italy",
    code: "IT",
    region: "Europe",
    population: "59 million",
    ecommerceRevenue: "$54 billion",
    ecommerceGrowth: "9.8%",
    topPlatforms: ["Amazon.it", "eBay.it", "ePrice", "Shopify"],
    paymentMethods: ["PostePay", "Credit Cards", "PayPal", "Cash on Delivery", "Satispay"],
    shippingConsiderations: "Poste Italiane and BRT. Cash on delivery common in South. Delivery delays possible.",
    consumerBehavior: "Brand-conscious. Quality-focused. Growing but cautious online shoppers.",
    topNiches: ["Fashion", "Food & wine", "Home decor", "Beauty", "Electronics"],
    challenges: ["Cash on delivery risk", "Shipping reliability", "Regional economic differences"],
    opportunities: ["Large population", "Fashion and design focus", "Growing ecommerce adoption"],
    vatTax: "22% VAT",
    currency: "EUR",
    language: "Italian",
    tier: "A"
  },
  {
    slug: "japan",
    name: "Japan",
    code: "JP",
    region: "Asia",
    population: "125 million",
    ecommerceRevenue: "$180 billion",
    ecommerceGrowth: "6.5%",
    topPlatforms: ["Amazon Japan", "Rakuten", "Yahoo! Shopping", "Mercari"],
    paymentMethods: ["Credit Cards", "Convenience Store Payment", "PayPay", "Bank Transfer"],
    shippingConsiderations: "Extremely fast delivery expected. Convenience store pickup popular. High packaging standards.",
    consumerBehavior: "Quality-obsessed. Detail-oriented. High service expectations.",
    topNiches: ["Electronics", "Fashion", "Beauty", "Anime/manga merchandise", "Health products"],
    challenges: ["Language barrier", "High quality expectations", "Complex market entry"],
    opportunities: ["High purchasing power", "Aging population products", "Unique product demand"],
    vatTax: "10% consumption tax",
    currency: "JPY",
    language: "Japanese",
    tier: "A"
  },
  {
    slug: "brazil",
    name: "Brazil",
    code: "BR",
    region: "South America",
    population: "215 million",
    ecommerceRevenue: "$50 billion",
    ecommerceGrowth: "14.5%",
    topPlatforms: ["Mercado Libre", "Amazon Brazil", "Magazine Luiza", "Shopee"],
    paymentMethods: ["Pix", "Boleto", "Credit Cards (installments)", "Digital Wallets"],
    shippingConsiderations: "Correios postal service. Long delivery times to remote areas. Import duties high.",
    consumerBehavior: "Installment payments crucial. Price-sensitive. Mobile-first market.",
    topNiches: ["Fashion", "Electronics", "Beauty", "Home appliances", "Sports"],
    challenges: ["Import taxes (60%+)", "Payment complexity", "Shipping infrastructure"],
    opportunities: ["Large population", "Growing middle class", "High mobile usage"],
    vatTax: "Varies by state + import duties",
    currency: "BRL",
    language: "Portuguese",
    tier: "B"
  },
  {
    slug: "mexico",
    name: "Mexico",
    code: "MX",
    region: "North America",
    population: "130 million",
    ecommerceRevenue: "$45 billion",
    ecommerceGrowth: "18.2%",
    topPlatforms: ["Mercado Libre", "Amazon Mexico", "Walmart Mexico", "Shopify"],
    paymentMethods: ["Credit Cards", "OXXO (cash)", "PayPal", "Mercado Pago", "Debit Cards"],
    shippingConsiderations: "Estafeta and FedEx common. Cash payment at OXXO popular. USMCA benefits.",
    consumerBehavior: "Growing online trust. Installment payments preferred. Mobile commerce rising.",
    topNiches: ["Fashion", "Electronics", "Beauty", "Home goods", "Sports"],
    challenges: ["Cash payment logistics", "Shipping reliability", "Trust building"],
    opportunities: ["Fast growth", "USMCA benefits", "Young population"],
    vatTax: "16% IVA",
    currency: "MXN",
    language: "Spanish",
    tier: "B"
  },
  {
    slug: "india",
    name: "India",
    code: "IN",
    region: "Asia",
    population: "1.4 billion",
    ecommerceRevenue: "$100 billion",
    ecommerceGrowth: "25.5%",
    topPlatforms: ["Amazon India", "Flipkart", "Meesho", "Shopify"],
    paymentMethods: ["UPI", "Cash on Delivery", "Credit Cards", "Paytm", "PhonePe"],
    shippingConsiderations: "Cash on delivery dominant. Delhivery and BlueDart common. Tier 2/3 cities growing.",
    consumerBehavior: "Extremely price-sensitive. Mobile-first. Social commerce exploding.",
    topNiches: ["Fashion", "Electronics", "Beauty", "Home decor", "Kids products"],
    challenges: ["Low margins", "COD returns", "Logistics to rural areas"],
    opportunities: ["Massive population", "Fast growth", "Rising middle class"],
    vatTax: "18% GST (varies by product)",
    currency: "INR",
    language: "Hindi, English",
    tier: "B"
  },
  {
    slug: "south-korea",
    name: "South Korea",
    code: "KR",
    region: "Asia",
    population: "52 million",
    ecommerceRevenue: "$140 billion",
    ecommerceGrowth: "9.2%",
    topPlatforms: ["Coupang", "11Street", "Gmarket", "Naver Shopping"],
    paymentMethods: ["Credit Cards", "Kakao Pay", "Naver Pay", "Samsung Pay"],
    shippingConsiderations: "Same-day delivery standard. Coupang Rocket Delivery. High expectations.",
    consumerBehavior: "Tech-savvy. Fast adoption. Quality and brand conscious.",
    topNiches: ["Beauty (K-beauty)", "Fashion", "Electronics", "Food", "Health"],
    challenges: ["Extreme delivery expectations", "Local platform dominance", "Language"],
    opportunities: ["High spending power", "Tech adoption", "K-culture export"],
    vatTax: "10% VAT",
    currency: "KRW",
    language: "Korean",
    tier: "A"
  },
  {
    slug: "indonesia",
    name: "Indonesia",
    code: "ID",
    region: "Southeast Asia",
    population: "275 million",
    ecommerceRevenue: "$62 billion",
    ecommerceGrowth: "20.1%",
    topPlatforms: ["Tokopedia", "Shopee", "Lazada", "Bukalapak", "TikTok Shop"],
    paymentMethods: ["Bank Transfer", "GoPay", "OVO", "Credit Cards", "COD"],
    shippingConsiderations: "Island logistics complex. JNE and J&T Express common. COD widespread.",
    consumerBehavior: "Mobile-first. Social commerce dominant. Price-sensitive.",
    topNiches: ["Fashion", "Beauty", "Electronics", "Muslim fashion", "Home goods"],
    challenges: ["Logistics complexity", "Low margins", "Island shipping"],
    opportunities: ["Huge population", "TikTok Shop growth", "Young demographic"],
    vatTax: "11% VAT",
    currency: "IDR",
    language: "Indonesian",
    tier: "B"
  },
  {
    slug: "uae",
    name: "United Arab Emirates",
    code: "AE",
    region: "Middle East",
    population: "10 million",
    ecommerceRevenue: "$8 billion",
    ecommerceGrowth: "15.8%",
    topPlatforms: ["Amazon.ae (Souq)", "Noon", "Namshi", "Shopify"],
    paymentMethods: ["Credit Cards", "Cash on Delivery", "Apple Pay", "Tabby"],
    shippingConsiderations: "Aramex and Emirates Post. Fast delivery in Dubai/Abu Dhabi.",
    consumerBehavior: "Luxury-focused. Brand conscious. High purchasing power.",
    topNiches: ["Luxury goods", "Fashion", "Electronics", "Beauty", "Home decor"],
    challenges: ["Cash on delivery", "Summer heat for products", "Customs"],
    opportunities: ["High income", "Tax-free shopping", "Expat population"],
    vatTax: "5% VAT",
    currency: "AED",
    language: "Arabic, English",
    tier: "A"
  },
  {
    slug: "saudi-arabia",
    name: "Saudi Arabia",
    code: "SA",
    region: "Middle East",
    population: "36 million",
    ecommerceRevenue: "$12 billion",
    ecommerceGrowth: "18.5%",
    topPlatforms: ["Amazon.sa", "Noon", "Namshi", "Jarir"],
    paymentMethods: ["Credit Cards", "Mada", "Apple Pay", "COD", "Tamara"],
    shippingConsiderations: "SMSA and Aramex common. Growing logistics infrastructure.",
    consumerBehavior: "Young population. Mobile-dominant. Brand and quality focused.",
    topNiches: ["Fashion", "Electronics", "Beauty", "Home goods", "Gaming"],
    challenges: ["Cultural considerations", "COD prevalence", "Customs process"],
    opportunities: ["Young population", "Vision 2030 growth", "High disposable income"],
    vatTax: "15% VAT",
    currency: "SAR",
    language: "Arabic",
    tier: "A"
  },
  {
    slug: "singapore",
    name: "Singapore",
    code: "SG",
    region: "Southeast Asia",
    population: "6 million",
    ecommerceRevenue: "$7 billion",
    ecommerceGrowth: "11.2%",
    topPlatforms: ["Shopee", "Lazada", "Amazon SG", "Qoo10"],
    paymentMethods: ["Credit Cards", "PayNow", "GrabPay", "PayPal"],
    shippingConsiderations: "Small country, fast delivery. SingPost and Ninja Van.",
    consumerBehavior: "Tech-savvy. Quality-conscious. Cross-border shopping common.",
    topNiches: ["Electronics", "Fashion", "Beauty", "Home goods", "Food"],
    challenges: ["Small market", "High competition", "Price transparency"],
    opportunities: ["High income", "English-speaking", "Regional gateway"],
    vatTax: "9% GST",
    currency: "SGD",
    language: "English, Mandarin, Malay, Tamil",
    tier: "A"
  },
  {
    slug: "philippines",
    name: "Philippines",
    code: "PH",
    region: "Southeast Asia",
    population: "115 million",
    ecommerceRevenue: "$18 billion",
    ecommerceGrowth: "24.1%",
    topPlatforms: ["Shopee", "Lazada", "TikTok Shop", "Zalora"],
    paymentMethods: ["GCash", "Maya", "COD", "Credit Cards", "Bank Transfer"],
    shippingConsiderations: "Island logistics. J&T and LBC common. COD dominant.",
    consumerBehavior: "Social commerce focused. Mobile-first. Price-sensitive but brand-aware.",
    topNiches: ["Fashion", "Beauty", "Electronics", "Home goods", "K-beauty"],
    challenges: ["Island shipping", "COD returns", "Lower purchasing power"],
    opportunities: ["Large population", "English-speaking", "TikTok Shop growth"],
    vatTax: "12% VAT",
    currency: "PHP",
    language: "Filipino, English",
    tier: "B"
  },
  {
    slug: "thailand",
    name: "Thailand",
    code: "TH",
    region: "Southeast Asia",
    population: "70 million",
    ecommerceRevenue: "$25 billion",
    ecommerceGrowth: "16.8%",
    topPlatforms: ["Shopee", "Lazada", "TikTok Shop", "JD Central"],
    paymentMethods: ["PromptPay", "Credit Cards", "COD", "TrueMoney", "Line Pay"],
    shippingConsiderations: "Kerry Express and Flash Express. Bangkok fast, provinces slower.",
    consumerBehavior: "Social commerce heavy. Live selling popular. Brand-conscious.",
    topNiches: ["Beauty", "Fashion", "Electronics", "Home goods", "Food"],
    challenges: ["Language barrier", "Live selling competition", "Regional logistics"],
    opportunities: ["Growing market", "Social commerce", "TikTok Shop leader"],
    vatTax: "7% VAT",
    currency: "THB",
    language: "Thai",
    tier: "B"
  },
  {
    slug: "vietnam",
    name: "Vietnam",
    code: "VN",
    region: "Southeast Asia",
    population: "100 million",
    ecommerceRevenue: "$20 billion",
    ecommerceGrowth: "28.5%",
    topPlatforms: ["Shopee", "Lazada", "Tiki", "TikTok Shop"],
    paymentMethods: ["COD", "MoMo", "ZaloPay", "Bank Transfer", "Credit Cards"],
    shippingConsiderations: "GHN and Viettel Post common. COD standard. Urban focus.",
    consumerBehavior: "Young population. Mobile-dominant. Live commerce growing fast.",
    topNiches: ["Fashion", "Beauty", "Electronics", "Mother & baby", "Home goods"],
    challenges: ["COD prevalence", "Language", "Low margins"],
    opportunities: ["Fast growth", "Young population", "Manufacturing hub"],
    vatTax: "10% VAT",
    currency: "VND",
    language: "Vietnamese",
    tier: "B"
  },
  {
    slug: "poland",
    name: "Poland",
    code: "PL",
    region: "Europe",
    population: "38 million",
    ecommerceRevenue: "$22 billion",
    ecommerceGrowth: "12.5%",
    topPlatforms: ["Allegro", "Amazon.pl", "OLX", "Shopify"],
    paymentMethods: ["BLIK", "PayU", "Credit Cards", "PayPal", "Cash on Delivery"],
    shippingConsiderations: "InPost parcel lockers dominant. Poczta Polska. Fast EU shipping.",
    consumerBehavior: "Price-conscious. Growing online trust. Parcel locker preference.",
    topNiches: ["Electronics", "Fashion", "Home & garden", "Sports", "Books"],
    challenges: ["Allegro dominance", "BLIK payment setup", "Language"],
    opportunities: ["Large EU market", "Growing ecommerce", "InPost convenience"],
    vatTax: "23% VAT",
    currency: "PLN",
    language: "Polish",
    tier: "A"
  },
  {
    slug: "sweden",
    name: "Sweden",
    code: "SE",
    region: "Europe",
    population: "10.5 million",
    ecommerceRevenue: "$18 billion",
    ecommerceGrowth: "7.8%",
    topPlatforms: ["Amazon.se", "CDON", "Zalando", "Shopify"],
    paymentMethods: ["Swish", "Klarna", "Credit Cards", "Invoice"],
    shippingConsiderations: "PostNord and DHL. Fast delivery expected. Sustainability important.",
    consumerBehavior: "Sustainability-focused. High digital adoption. Quality over price.",
    topNiches: ["Sustainable products", "Outdoor gear", "Fashion", "Home goods", "Tech"],
    challenges: ["Small market", "High sustainability expectations", "Seasonal"],
    opportunities: ["High income", "Eco-conscious consumers", "Klarna home market"],
    vatTax: "25% VAT",
    currency: "SEK",
    language: "Swedish, English widely spoken",
    tier: "A"
  },
  {
    slug: "belgium",
    name: "Belgium",
    code: "BE",
    region: "Europe",
    population: "11.5 million",
    ecommerceRevenue: "$15 billion",
    ecommerceGrowth: "8.2%",
    topPlatforms: ["Bol.com", "Amazon", "Coolblue", "Zalando"],
    paymentMethods: ["Bancontact", "Credit Cards", "PayPal", "Klarna"],
    shippingConsiderations: "bpost and PostNL. Cross-border from NL easy. Bilingual market.",
    consumerBehavior: "Quality-conscious. Cross-border shopping common. Bilingual complexity.",
    topNiches: ["Electronics", "Fashion", "Home goods", "Food", "Sports"],
    challenges: ["Bilingual (Dutch/French)", "Small market", "Local competition"],
    opportunities: ["High income", "EU logistics hub", "Cross-border friendly"],
    vatTax: "21% VAT",
    currency: "EUR",
    language: "Dutch, French, German",
    tier: "A"
  },
  {
    slug: "austria",
    name: "Austria",
    code: "AT",
    region: "Europe",
    population: "9 million",
    ecommerceRevenue: "$12 billion",
    ecommerceGrowth: "7.5%",
    topPlatforms: ["Amazon.de", "Willhaben", "Zalando", "Shopify"],
    paymentMethods: ["Credit Cards", "PayPal", "EPS", "Klarna", "Invoice"],
    shippingConsiderations: "Austrian Post and DHL. German Amazon ships easily.",
    consumerBehavior: "Quality-focused. German-speaking. Cross-border shopping common.",
    topNiches: ["Outdoor sports", "Fashion", "Electronics", "Home goods", "Organic products"],
    challenges: ["Small market", "German competition", "High quality expectations"],
    opportunities: ["High income", "German language", "Quality-conscious consumers"],
    vatTax: "20% VAT",
    currency: "EUR",
    language: "German",
    tier: "A"
  },
  {
    slug: "switzerland",
    name: "Switzerland",
    code: "CH",
    region: "Europe",
    population: "8.7 million",
    ecommerceRevenue: "$14 billion",
    ecommerceGrowth: "6.8%",
    topPlatforms: ["Galaxus", "Amazon.de", "Zalando", "Shopify"],
    paymentMethods: ["Credit Cards", "TWINT", "PostFinance", "PayPal", "Invoice"],
    shippingConsiderations: "Swiss Post excellent. Non-EU customs considerations. Premium expectations.",
    consumerBehavior: "Highest purchasing power. Quality-obsessed. Privacy-conscious.",
    topNiches: ["Luxury goods", "Watches", "Outdoor gear", "Electronics", "Organic products"],
    challenges: ["Non-EU customs", "High expectations", "Expensive market entry"],
    opportunities: ["Highest income", "Premium product demand", "Quality appreciation"],
    vatTax: "8.1% VAT",
    currency: "CHF",
    language: "German, French, Italian",
    tier: "A"
  },
  {
    slug: "ireland",
    name: "Ireland",
    code: "IE",
    region: "Europe",
    population: "5 million",
    ecommerceRevenue: "$6 billion",
    ecommerceGrowth: "9.5%",
    topPlatforms: ["Amazon UK", "Shopify", "DoneDeal", "Zalando"],
    paymentMethods: ["Credit Cards", "PayPal", "Revolut", "Apple Pay"],
    shippingConsiderations: "An Post and DPD. UK shipping post-Brexit complex.",
    consumerBehavior: "English-speaking. UK shopping habits. Growing local preference.",
    topNiches: ["Fashion", "Electronics", "Home goods", "Sports", "Books"],
    challenges: ["Small market", "Brexit shipping from UK", "Local competition"],
    opportunities: ["English-speaking EU", "High income", "Tech-savvy population"],
    vatTax: "23% VAT",
    currency: "EUR",
    language: "English, Irish",
    tier: "A"
  },
  {
    slug: "new-zealand",
    name: "New Zealand",
    code: "NZ",
    region: "Oceania",
    population: "5 million",
    ecommerceRevenue: "$6 billion",
    ecommerceGrowth: "10.2%",
    topPlatforms: ["Trade Me", "Amazon AU", "Mighty Ape", "Shopify"],
    paymentMethods: ["Credit Cards", "PayPal", "Afterpay", "Laybuy"],
    shippingConsiderations: "NZ Post. Long international shipping. Biosecurity strict.",
    consumerBehavior: "Outdoor lifestyle. Quality-conscious. BNPL adopters.",
    topNiches: ["Outdoor gear", "Sports", "Home goods", "Pet products", "Sustainable products"],
    challenges: ["Small market", "Remote location", "Biosecurity restrictions"],
    opportunities: ["High income", "English-speaking", "Eco-conscious consumers"],
    vatTax: "15% GST",
    currency: "NZD",
    language: "English, Māori",
    tier: "B"
  },
  {
    slug: "norway",
    name: "Norway",
    code: "NO",
    region: "Europe",
    population: "5.4 million",
    ecommerceRevenue: "$10 billion",
    ecommerceGrowth: "8.1%",
    topPlatforms: ["Komplett", "Amazon.de", "Zalando", "Shopify"],
    paymentMethods: ["Vipps", "Credit Cards", "Klarna", "PayPal"],
    shippingConsiderations: "Posten Norge. Non-EU customs. Remote areas costly.",
    consumerBehavior: "Highest purchasing power. Outdoor lifestyle. Sustainability-focused.",
    topNiches: ["Outdoor gear", "Electronics", "Sustainable products", "Fashion", "Sports"],
    challenges: ["Non-EU customs", "Small market", "Expensive logistics"],
    opportunities: ["Highest income globally", "Quality appreciation", "Eco-focus"],
    vatTax: "25% VAT",
    currency: "NOK",
    language: "Norwegian, English widely spoken",
    tier: "A"
  },
  {
    slug: "denmark",
    name: "Denmark",
    code: "DK",
    region: "Europe",
    population: "5.9 million",
    ecommerceRevenue: "$13 billion",
    ecommerceGrowth: "7.9%",
    topPlatforms: ["Amazon.de", "Zalando", "Proshop", "Shopify"],
    paymentMethods: ["MobilePay", "Credit Cards", "Klarna", "PayPal"],
    shippingConsiderations: "PostNord Danmark. Fast EU shipping. MobilePay dominant.",
    consumerBehavior: "Design-conscious. Sustainability-focused. High digital adoption.",
    topNiches: ["Design products", "Fashion", "Electronics", "Home goods", "Cycling gear"],
    challenges: ["Small market", "MobilePay requirement", "High expectations"],
    opportunities: ["High income", "Design appreciation", "Eco-conscious"],
    vatTax: "25% VAT",
    currency: "DKK",
    language: "Danish, English widely spoken",
    tier: "A"
  },
  {
    slug: "finland",
    name: "Finland",
    code: "FI",
    region: "Europe",
    population: "5.5 million",
    ecommerceRevenue: "$9 billion",
    ecommerceGrowth: "8.5%",
    topPlatforms: ["Amazon.de", "Verkkokauppa", "Zalando", "Shopify"],
    paymentMethods: ["Online Banking", "Credit Cards", "Klarna", "MobilePay"],
    shippingConsiderations: "Posti Finland. Parcel lockers popular. Long distances.",
    consumerBehavior: "Tech-savvy. Quality-focused. Outdoor lifestyle.",
    topNiches: ["Electronics", "Outdoor gear", "Home goods", "Fashion", "Sauna products"],
    challenges: ["Small market", "Remote areas", "Long winters"],
    opportunities: ["High income", "Tech adoption", "Unique product opportunities"],
    vatTax: "24% VAT",
    currency: "EUR",
    language: "Finnish, Swedish, English",
    tier: "A"
  },
  {
    slug: "portugal",
    name: "Portugal",
    code: "PT",
    region: "Europe",
    population: "10 million",
    ecommerceRevenue: "$8 billion",
    ecommerceGrowth: "11.5%",
    topPlatforms: ["Amazon.es", "Worten", "KuantoKusta", "Shopify"],
    paymentMethods: ["MB WAY", "Credit Cards", "PayPal", "Multibanco"],
    shippingConsiderations: "CTT Portugal. Spanish Amazon ships easily.",
    consumerBehavior: "Growing online shopping. Price-conscious. Mobile adoption rising.",
    topNiches: ["Electronics", "Fashion", "Home goods", "Sports", "Beauty"],
    challenges: ["MB WAY integration", "Lower purchasing power", "Small market"],
    opportunities: ["Growing market", "Tourism influence", "Portuguese-speaking base"],
    vatTax: "23% VAT",
    currency: "EUR",
    language: "Portuguese",
    tier: "B"
  },
  {
    slug: "czech-republic",
    name: "Czech Republic",
    code: "CZ",
    region: "Europe",
    population: "10.5 million",
    ecommerceRevenue: "$10 billion",
    ecommerceGrowth: "13.2%",
    topPlatforms: ["Alza.cz", "Mall.cz", "Amazon.de", "Shopify"],
    paymentMethods: ["Bank Transfer", "Credit Cards", "PayPal", "COD"],
    shippingConsiderations: "Zásilkovna lockers popular. PPL and DPD common.",
    consumerBehavior: "Price-sensitive. Tech-savvy. Growing ecommerce adoption.",
    topNiches: ["Electronics", "Home goods", "Fashion", "Sports", "Books"],
    challenges: ["Local platform dominance", "Czech language", "COD preference"],
    opportunities: ["Growing market", "EU member", "Parcel locker adoption"],
    vatTax: "21% VAT",
    currency: "CZK",
    language: "Czech",
    tier: "B"
  },
  {
    slug: "romania",
    name: "Romania",
    code: "RO",
    region: "Europe",
    population: "19 million",
    ecommerceRevenue: "$8 billion",
    ecommerceGrowth: "15.8%",
    topPlatforms: ["eMAG", "Amazon.de", "OLX", "Shopify"],
    paymentMethods: ["Cash on Delivery", "Credit Cards", "PayPal", "Bank Transfer"],
    shippingConsiderations: "Fan Courier and Cargus common. COD dominant.",
    consumerBehavior: "Price-sensitive. COD preference. Growing trust.",
    topNiches: ["Electronics", "Fashion", "Home appliances", "Beauty", "Sports"],
    challenges: ["COD returns", "Lower purchasing power", "eMAG dominance"],
    opportunities: ["Growing market", "EU member", "Young population"],
    vatTax: "19% VAT",
    currency: "RON",
    language: "Romanian",
    tier: "B"
  },
  {
    slug: "hungary",
    name: "Hungary",
    code: "HU",
    region: "Europe",
    population: "9.7 million",
    ecommerceRevenue: "$5 billion",
    ecommerceGrowth: "14.2%",
    topPlatforms: ["eMAG Hungary", "Alza.hu", "Amazon.de", "Shopify"],
    paymentMethods: ["Credit Cards", "Bank Transfer", "COD", "PayPal"],
    shippingConsiderations: "GLS and DPD common. Foxpost lockers growing.",
    consumerBehavior: "Price-conscious. Growing online adoption. Quality awareness.",
    topNiches: ["Electronics", "Home goods", "Fashion", "Sports", "Books"],
    challenges: ["Small market", "Local competition", "Language barrier"],
    opportunities: ["Growing market", "EU logistics", "Central European hub"],
    vatTax: "27% VAT",
    currency: "HUF",
    language: "Hungarian",
    tier: "B"
  },
  {
    slug: "greece",
    name: "Greece",
    code: "GR",
    region: "Europe",
    population: "10.4 million",
    ecommerceRevenue: "$6 billion",
    ecommerceGrowth: "12.8%",
    topPlatforms: ["Skroutz", "Amazon.de", "Public.gr", "Shopify"],
    paymentMethods: ["Credit Cards", "Cash on Delivery", "PayPal", "Viva Wallet"],
    shippingConsiderations: "ACS and Speedex common. Island shipping complex.",
    consumerBehavior: "Price comparison via Skroutz. COD still common. Growing trust.",
    topNiches: ["Electronics", "Fashion", "Home goods", "Beauty", "Sports"],
    challenges: ["Skroutz price transparency", "Island logistics", "COD preference"],
    opportunities: ["Growing market", "Tourism influence", "EU member"],
    vatTax: "24% VAT",
    currency: "EUR",
    language: "Greek",
    tier: "B"
  },
  {
    slug: "israel",
    name: "Israel",
    code: "IL",
    region: "Middle East",
    population: "9.5 million",
    ecommerceRevenue: "$10 billion",
    ecommerceGrowth: "11.5%",
    topPlatforms: ["Amazon", "AliExpress", "KSP", "Shopify"],
    paymentMethods: ["Credit Cards", "PayPal", "Bit", "Apple Pay"],
    shippingConsiderations: "Israel Post. Import duties and VAT. Security checks.",
    consumerBehavior: "Tech-savvy. Cross-border shopping. Price-conscious.",
    topNiches: ["Electronics", "Fashion", "Baby products", "Home goods", "Health"],
    challenges: ["Import duties", "Shipping times", "Security delays"],
    opportunities: ["High tech adoption", "Strong purchasing power", "English proficiency"],
    vatTax: "17% VAT",
    currency: "ILS",
    language: "Hebrew, English",
    tier: "A"
  },
  {
    slug: "south-africa",
    name: "South Africa",
    code: "ZA",
    region: "Africa",
    population: "60 million",
    ecommerceRevenue: "$5 billion",
    ecommerceGrowth: "18.5%",
    topPlatforms: ["Takealot", "Amazon", "Shopify", "Superbalist"],
    paymentMethods: ["Credit Cards", "EFT", "SnapScan", "Payflex"],
    shippingConsiderations: "The Courier Guy and Dawn Wing. Urban-focused delivery.",
    consumerBehavior: "Growing middle class. Mobile commerce. Price-sensitive.",
    topNiches: ["Electronics", "Fashion", "Beauty", "Home goods", "Sports"],
    challenges: ["Economic volatility", "Logistics infrastructure", "Crime concerns"],
    opportunities: ["Largest African market", "Growing middle class", "English-speaking"],
    vatTax: "15% VAT",
    currency: "ZAR",
    language: "English, Afrikaans, Zulu + 8 others",
    tier: "B"
  },
  {
    slug: "malaysia",
    name: "Malaysia",
    code: "MY",
    region: "Southeast Asia",
    population: "33 million",
    ecommerceRevenue: "$12 billion",
    ecommerceGrowth: "16.5%",
    topPlatforms: ["Shopee", "Lazada", "TikTok Shop", "Zalora"],
    paymentMethods: ["FPX", "Credit Cards", "GrabPay", "Touch 'n Go", "COD"],
    shippingConsiderations: "J&T and Poslaju common. West/East Malaysia logistics differ.",
    consumerBehavior: "Mobile-first. Social commerce growing. Multi-cultural market.",
    topNiches: ["Fashion", "Beauty", "Electronics", "Muslim fashion", "Home goods"],
    challenges: ["Multi-ethnic marketing", "East Malaysia logistics", "Platform fees"],
    opportunities: ["Growing market", "English proficiency", "TikTok Shop growth"],
    vatTax: "6% SST on selected items",
    currency: "MYR",
    language: "Malay, English, Mandarin, Tamil",
    tier: "B"
  },
  {
    slug: "taiwan",
    name: "Taiwan",
    code: "TW",
    region: "Asia",
    population: "24 million",
    ecommerceRevenue: "$35 billion",
    ecommerceGrowth: "8.8%",
    topPlatforms: ["Shopee", "PChome", "Momo", "Rakuten Taiwan"],
    paymentMethods: ["Credit Cards", "Convenience Store Payment", "LINE Pay", "JKoPay"],
    shippingConsiderations: "7-Eleven and FamilyMart pickup dominant. Fast delivery.",
    consumerBehavior: "Convenience store culture. Tech-savvy. Quality-conscious.",
    topNiches: ["Electronics", "Fashion", "Beauty", "Food", "Gaming"],
    challenges: ["Language barrier", "Local platform dominance", "Small market"],
    opportunities: ["High purchasing power", "Tech adoption", "Quality appreciation"],
    vatTax: "5% VAT",
    currency: "TWD",
    language: "Mandarin",
    tier: "A"
  },
  {
    slug: "hong-kong",
    name: "Hong Kong",
    code: "HK",
    region: "Asia",
    population: "7.5 million",
    ecommerceRevenue: "$15 billion",
    ecommerceGrowth: "9.2%",
    topPlatforms: ["HKTVmall", "Amazon", "Taobao", "Shopify"],
    paymentMethods: ["Credit Cards", "AlipayHK", "PayMe", "FPS"],
    shippingConsiderations: "SF Express and Hongkong Post. Dense city, fast delivery.",
    consumerBehavior: "Cross-border shopping. Brand-conscious. Mobile payments.",
    topNiches: ["Fashion", "Beauty", "Electronics", "Luxury goods", "Health"],
    challenges: ["Small market", "Taobao competition", "High rent/costs"],
    opportunities: ["High income", "China gateway", "English/Chinese bilingual"],
    vatTax: "No VAT/sales tax",
    currency: "HKD",
    language: "Cantonese, English, Mandarin",
    tier: "A"
  },
  {
    slug: "argentina",
    name: "Argentina",
    code: "AR",
    region: "South America",
    population: "46 million",
    ecommerceRevenue: "$15 billion",
    ecommerceGrowth: "22.5%",
    topPlatforms: ["Mercado Libre", "Amazon", "Shopify"],
    paymentMethods: ["Mercado Pago", "Credit Cards (installments)", "Bank Transfer"],
    shippingConsiderations: "Andreani and OCA. Import restrictions. Currency volatility.",
    consumerBehavior: "Installment payments essential. Price-sensitive. Growing online.",
    topNiches: ["Electronics", "Fashion", "Home goods", "Sports", "Beauty"],
    challenges: ["Import restrictions", "Currency volatility", "Economic instability"],
    opportunities: ["Large population", "Growing ecommerce", "Mercado Libre dominance"],
    vatTax: "21% IVA",
    currency: "ARS",
    language: "Spanish",
    tier: "C"
  },
  {
    slug: "colombia",
    name: "Colombia",
    code: "CO",
    region: "South America",
    population: "52 million",
    ecommerceRevenue: "$12 billion",
    ecommerceGrowth: "20.5%",
    topPlatforms: ["Mercado Libre", "Falabella", "Amazon", "Shopify"],
    paymentMethods: ["Credit Cards", "PSE", "Cash on Delivery", "Nequi"],
    shippingConsiderations: "Servientrega and Coordinadora. Urban-focused.",
    consumerBehavior: "Growing online adoption. Price-sensitive. Mobile commerce rising.",
    topNiches: ["Fashion", "Electronics", "Beauty", "Home goods", "Sports"],
    challenges: ["Payment infrastructure", "Rural logistics", "Lower purchasing power"],
    opportunities: ["Large population", "Growing middle class", "Improving infrastructure"],
    vatTax: "19% IVA",
    currency: "COP",
    language: "Spanish",
    tier: "B"
  },
  {
    slug: "chile",
    name: "Chile",
    code: "CL",
    region: "South America",
    population: "19 million",
    ecommerceRevenue: "$10 billion",
    ecommerceGrowth: "15.8%",
    topPlatforms: ["Mercado Libre", "Falabella", "Amazon", "Shopify"],
    paymentMethods: ["Credit Cards", "Webpay", "Mercado Pago", "Bank Transfer"],
    shippingConsiderations: "Chilexpress and Starken. Long country logistics.",
    consumerBehavior: "Highest income in LatAm. Quality-conscious. Growing ecommerce.",
    topNiches: ["Electronics", "Fashion", "Home goods", "Outdoor gear", "Beauty"],
    challenges: ["Long country logistics", "Small market", "Import duties"],
    opportunities: ["Highest LatAm income", "Stable economy", "Growing ecommerce"],
    vatTax: "19% IVA",
    currency: "CLP",
    language: "Spanish",
    tier: "B"
  }
];

export const getCountryBySlug = (slug: string): Country | undefined => {
  return countries.find((c) => c.slug === slug);
};

export const getAllCountries = (): Country[] => {
  return countries;
};

export const getCountriesByRegion = (region: string): Country[] => {
  return countries.filter((c) => c.region === region);
};

export const getCountriesByTier = (tier: Country["tier"]): Country[] => {
  return countries.filter((c) => c.tier === tier);
};

export const getRegions = (): string[] => {
  return [...new Set(countries.map((c) => c.region))];
};
