export type Supplier = {
  slug: string;
  name: string;
  description: string;
  headquarters: string;
  founded: string;
  website: string;
  categories: string[];
  shippingTime: string;
  minOrder: string;
  pricing: string;
  platforms: string[];
  pros: string[];
  cons: string[];
  bestFor: string;
  rating: number;
  features: string[];
};

export const suppliers: Supplier[] = [
  {
    slug: "zendrop",
    name: "Zendrop",
    description: "All-in-one dropshipping platform with direct manufacturer relationships and US warehouses for faster shipping.",
    headquarters: "United States",
    founded: "2020",
    website: "zendrop.com",
    categories: ["general", "electronics", "fashion", "home", "beauty"],
    shippingTime: "5-8 days (US)",
    minOrder: "No minimum",
    pricing: "Free plan, Pro from $49/mo",
    platforms: ["Shopify", "WooCommerce", "BigCommerce", "Wix"],
    pros: ["Fast US shipping", "Branded packaging", "Direct manufacturer pricing", "Automation tools", "Product sourcing requests"],
    cons: ["Higher prices than AliExpress", "Limited product catalog vs AliExpress", "Pro features require subscription"],
    bestFor: "US-focused stores wanting faster shipping and branding options",
    rating: 4.6,
    features: ["Auto-fulfillment", "Branded invoicing", "Bundle products", "Subscription boxes", "Express shipping"]
  },
  {
    slug: "cj-dropshipping",
    name: "CJ Dropshipping",
    description: "Comprehensive dropshipping platform combining sourcing, warehousing, and fulfillment with global warehouse network.",
    headquarters: "China",
    founded: "2014",
    website: "cjdropshipping.com",
    categories: ["general", "electronics", "fashion", "home", "toys", "sports", "pet"],
    shippingTime: "7-12 days (with US warehouse)",
    minOrder: "No minimum",
    pricing: "Free to use, pay per order",
    platforms: ["Shopify", "WooCommerce", "eBay", "Etsy", "TikTok Shop"],
    pros: ["Free product sourcing", "Quality inspection", "Global warehouses", "Print on demand", "Video/photo service"],
    cons: ["Variable quality control", "Complex interface", "Shipping times vary"],
    bestFor: "Stores needing product sourcing and custom packaging at scale",
    rating: 4.4,
    features: ["Product sourcing", "Private labeling", "Quality inspection", "Photo/video service", "POD integration"]
  },
  {
    slug: "spocket",
    name: "Spocket",
    description: "Premium dropshipping platform connecting merchants with US and EU-based suppliers for faster delivery.",
    headquarters: "Canada",
    founded: "2017",
    website: "spocket.co",
    categories: ["fashion", "home", "beauty", "accessories", "jewelry"],
    shippingTime: "2-5 days (US/EU)",
    minOrder: "No minimum",
    pricing: "Free plan, Starter $39.99/mo",
    platforms: ["Shopify", "WooCommerce", "Wix", "BigCommerce", "Squarespace"],
    pros: ["Fast US/EU shipping", "Vetted suppliers", "Branded invoicing", "30-70% discounts", "Quality products"],
    cons: ["Smaller catalog", "Higher product costs", "Limited global suppliers"],
    bestFor: "Premium stores targeting US/EU customers with fast shipping expectations",
    rating: 4.5,
    features: ["Branded invoicing", "Real-time inventory", "Auto price updates", "Sample orders", "1-click import"]
  },
  {
    slug: "aliexpress",
    name: "AliExpress",
    description: "World's largest retail marketplace with millions of products at wholesale prices, popular for dropshipping.",
    headquarters: "China",
    founded: "2010",
    website: "aliexpress.com",
    categories: ["all categories"],
    shippingTime: "15-30 days (standard), 7-15 days (ePacket)",
    minOrder: "No minimum",
    pricing: "Free, wholesale prices",
    platforms: ["All platforms via DSers, Oberlo legacy"],
    pros: ["Massive product selection", "Lowest prices", "Buyer protection", "No minimums", "Easy to start"],
    cons: ["Long shipping times", "Quality inconsistency", "Limited branding", "Customer service issues"],
    bestFor: "Beginners testing products and budget-conscious sellers",
    rating: 4.0,
    features: ["Buyer protection", "Free shipping options", "Product reviews", "Seller ratings", "Dispute resolution"]
  },
  {
    slug: "dsers",
    name: "DSers",
    description: "Official AliExpress dropshipping partner providing automation for order processing and supplier management.",
    headquarters: "China",
    founded: "2018",
    website: "dsers.com",
    categories: ["all AliExpress categories"],
    shippingTime: "Depends on AliExpress supplier",
    minOrder: "No minimum",
    pricing: "Free plan, Advanced $19.90/mo",
    platforms: ["Shopify", "WooCommerce", "Wix"],
    pros: ["Bulk order processing", "Multiple stores", "Supplier optimizer", "Automatic tracking", "Bundle mapping"],
    cons: ["Dependent on AliExpress", "Learning curve", "Some features paid"],
    bestFor: "AliExpress sellers needing automation and bulk processing",
    rating: 4.3,
    features: ["Bulk orders", "Supplier optimizer", "Auto sync", "Variant mapping", "Multiple stores"]
  },
  {
    slug: "alibaba",
    name: "Alibaba",
    description: "B2B marketplace connecting businesses with manufacturers for bulk orders and private labeling.",
    headquarters: "China",
    founded: "1999",
    website: "alibaba.com",
    categories: ["all categories", "manufacturing"],
    shippingTime: "14-45 days (varies)",
    minOrder: "50-1000+ units typically",
    pricing: "Wholesale/bulk pricing",
    platforms: ["Direct ordering"],
    pros: ["Lowest bulk prices", "Direct manufacturer access", "Custom products", "Private labeling", "Trade assurance"],
    cons: ["High MOQs", "Complex negotiation", "Long lead times", "Quality risks"],
    bestFor: "Established sellers ready for bulk orders and private labeling",
    rating: 4.2,
    features: ["Trade assurance", "Verified suppliers", "RFQ system", "Factory audits", "Custom manufacturing"]
  },
  {
    slug: "printful",
    name: "Printful",
    description: "Premium print-on-demand and dropshipping company with global fulfillment centers and high-quality products.",
    headquarters: "United States",
    founded: "2013",
    website: "printful.com",
    categories: ["apparel", "accessories", "home decor", "drinkware"],
    shippingTime: "2-5 days production + shipping",
    minOrder: "No minimum",
    pricing: "Free, pay per product",
    platforms: ["Shopify", "WooCommerce", "Etsy", "Amazon", "eBay", "TikTok Shop"],
    pros: ["Premium quality", "Global fulfillment", "Mockup generator", "Warehousing", "Embroidery options"],
    cons: ["Higher prices", "Smaller margins", "Limited product range"],
    bestFor: "Brands wanting premium print-on-demand with consistent quality",
    rating: 4.7,
    features: ["Mockup generator", "Design maker", "Warehousing", "Custom branding", "Sample discounts"]
  },
  {
    slug: "printify",
    name: "Printify",
    description: "Print-on-demand platform connecting merchants to global print provider network for competitive pricing.",
    headquarters: "Latvia",
    founded: "2015",
    website: "printify.com",
    categories: ["apparel", "accessories", "home decor", "drinkware", "stationery"],
    shippingTime: "3-7 days production + shipping",
    minOrder: "No minimum",
    pricing: "Free plan, Premium $29/mo",
    platforms: ["Shopify", "WooCommerce", "Etsy", "eBay", "Wix"],
    pros: ["Multiple print providers", "Competitive prices", "Huge product catalog", "Easy design tool", "Shopify integration"],
    cons: ["Quality varies by provider", "Less control", "Support response time"],
    bestFor: "POD sellers wanting best prices through provider competition",
    rating: 4.5,
    features: ["Provider selection", "Automatic routing", "Mockup generator", "Sample orders", "Custom import"]
  },
  {
    slug: "doba",
    name: "Doba",
    description: "Dropshipping platform aggregating products from multiple suppliers into one searchable catalog.",
    headquarters: "United States",
    founded: "2002",
    website: "doba.com",
    categories: ["general", "electronics", "fashion", "home", "sports"],
    shippingTime: "3-7 days (US suppliers)",
    minOrder: "No minimum",
    pricing: "From $24.99/mo",
    platforms: ["Shopify", "BigCommerce", "Amazon", "eBay"],
    pros: ["Vetted US suppliers", "One catalog interface", "Inventory management", "Order automation"],
    cons: ["Monthly subscription", "Limited free trial", "Smaller selection"],
    bestFor: "US sellers wanting aggregated supplier access with fast shipping",
    rating: 4.1,
    features: ["Supplier aggregation", "Inventory alerts", "Order routing", "Data export", "Analytics"]
  },
  {
    slug: "salehoo",
    name: "SaleHoo",
    description: "Wholesale supplier directory and dropshipping platform with vetted suppliers and market research tools.",
    headquarters: "New Zealand",
    founded: "2005",
    website: "salehoo.com",
    categories: ["general", "electronics", "fashion", "home", "toys"],
    shippingTime: "Varies by supplier",
    minOrder: "Varies by supplier",
    pricing: "$67/year or $127 lifetime",
    platforms: ["Shopify", "WooCommerce"],
    pros: ["8000+ vetted suppliers", "Market research lab", "60-day guarantee", "Training resources"],
    cons: ["Directory model", "Extra supplier negotiation", "One-time research tool"],
    bestFor: "Entrepreneurs wanting to find and vet suppliers themselves",
    rating: 4.2,
    features: ["Supplier directory", "Market research", "Training courses", "Community forum", "Supplier ratings"]
  },
  {
    slug: "wholesale2b",
    name: "Wholesale2B",
    description: "Dropshipping platform with 1M+ products from various suppliers and direct integration to major marketplaces.",
    headquarters: "United States",
    founded: "2004",
    website: "wholesale2b.com",
    categories: ["general", "electronics", "fashion", "home", "automotive"],
    shippingTime: "3-10 days (US)",
    minOrder: "No minimum",
    pricing: "From $29.99/mo",
    platforms: ["Shopify", "WooCommerce", "BigCommerce", "Amazon", "eBay"],
    pros: ["1M+ products", "Amazon/eBay integration", "Automated fulfillment", "US suppliers"],
    cons: ["Interface dated", "Variable supplier quality", "Limited customization"],
    bestFor: "Multi-channel sellers on Amazon, eBay, and Shopify",
    rating: 4.0,
    features: ["Multi-marketplace", "Auto inventory", "Order automation", "Product feeds", "Tracking sync"]
  },
  {
    slug: "modalyst",
    name: "Modalyst",
    description: "Curated dropshipping marketplace featuring independent brands and AliExpress products with Wix partnership.",
    headquarters: "United States",
    founded: "2012",
    website: "modalyst.co",
    categories: ["fashion", "accessories", "beauty", "home"],
    shippingTime: "5-8 days (US brands)",
    minOrder: "No minimum",
    pricing: "Free plan, Pro $35/mo",
    platforms: ["Shopify", "Wix", "BigCommerce"],
    pros: ["Independent brands", "US/EU suppliers", "Unique products", "Low competition"],
    cons: ["Smaller catalog", "Higher prices", "Fashion-focused"],
    bestFor: "Fashion and lifestyle stores wanting unique, curated products",
    rating: 4.3,
    features: ["Brand partnerships", "Curated catalog", "Auto fulfillment", "Inventory sync", "Wix integration"]
  },
  {
    slug: "inventory-source",
    name: "Inventory Source",
    description: "Dropship automation platform connecting retailers to 230+ pre-integrated suppliers with full automation.",
    headquarters: "United States",
    founded: "2002",
    website: "inventorysource.com",
    categories: ["general", "electronics", "home", "outdoor", "pet"],
    shippingTime: "2-7 days (US suppliers)",
    minOrder: "No minimum",
    pricing: "From $99/mo (automation)",
    platforms: ["Shopify", "WooCommerce", "BigCommerce", "Amazon", "eBay"],
    pros: ["230+ suppliers", "Full automation", "Real-time inventory", "Multi-channel"],
    cons: ["Higher pricing", "Complex setup", "Supplier fees separate"],
    bestFor: "Serious dropshippers wanting enterprise-level automation",
    rating: 4.2,
    features: ["Supplier network", "Full automation", "Inventory rules", "Order routing", "Analytics"]
  },
  {
    slug: "topdawg",
    name: "TopDawg",
    description: "US-based wholesale dropship supplier network with verified suppliers and no minimum order requirements.",
    headquarters: "United States",
    founded: "2015",
    website: "topdawg.com",
    categories: ["general", "electronics", "home", "outdoor", "pet", "automotive"],
    shippingTime: "2-5 days (US)",
    minOrder: "No minimum",
    pricing: "Pay per order",
    platforms: ["Shopify", "WooCommerce", "eBay", "Amazon"],
    pros: ["US-based shipping", "No MOQ", "Verified suppliers", "Fast fulfillment"],
    cons: ["Smaller product range", "US-focused", "Basic interface"],
    bestFor: "US sellers wanting domestic shipping without minimums",
    rating: 4.4,
    features: ["US fulfillment", "Blind shipping", "Real-time inventory", "Order tracking", "API access"]
  },
  {
    slug: "dropcommerce",
    name: "DropCommerce",
    description: "North American dropshipping app connecting Shopify stores with 400+ US and Canadian suppliers.",
    headquarters: "Canada",
    founded: "2018",
    website: "dropcommerce.com",
    categories: ["home", "fashion", "beauty", "pet", "outdoor"],
    shippingTime: "3-5 days (US/Canada)",
    minOrder: "No minimum",
    pricing: "Free plan, Growth $29/mo",
    platforms: ["Shopify"],
    pros: ["3-5 day shipping", "30%+ margins guaranteed", "Branded invoicing", "Quality products"],
    cons: ["Shopify only", "Smaller catalog", "North America focused"],
    bestFor: "Shopify stores targeting North American customers",
    rating: 4.5,
    features: ["Guaranteed margins", "Fast shipping", "Quality vetting", "Branded packaging", "Sample orders"]
  },
  {
    slug: "gooten",
    name: "Gooten",
    description: "Print-on-demand platform with global manufacturing network and enterprise-level fulfillment capabilities.",
    headquarters: "United States",
    founded: "2013",
    website: "gooten.com",
    categories: ["apparel", "home decor", "accessories", "drinkware"],
    shippingTime: "3-8 days production + shipping",
    minOrder: "No minimum",
    pricing: "Free, pay per product",
    platforms: ["Shopify", "WooCommerce", "Etsy", "BigCommerce", "API"],
    pros: ["Global network", "Competitive pricing", "API access", "Enterprise features"],
    cons: ["Less brand recognition", "Variable quality", "Limited design tools"],
    bestFor: "Growing POD brands needing scalable fulfillment",
    rating: 4.2,
    features: ["Global manufacturing", "API integration", "ShipHub", "Automated routing", "Wholesale pricing"]
  },
  {
    slug: "dhgate",
    name: "DHgate",
    description: "B2B/B2C Chinese marketplace with wholesale pricing and dropshipping capabilities for global buyers.",
    headquarters: "China",
    founded: "2004",
    website: "dhgate.com",
    categories: ["fashion", "electronics", "sports", "jewelry", "home"],
    shippingTime: "10-25 days",
    minOrder: "Low MOQs (often 1-5 units)",
    pricing: "Wholesale prices",
    platforms: ["Direct ordering"],
    pros: ["Low MOQs", "Competitive pricing", "Buyer protection", "Large catalog"],
    cons: ["Shipping times", "Quality varies", "Less dropship automation"],
    bestFor: "Sellers wanting bulk discounts with low minimum orders",
    rating: 3.9,
    features: ["Buyer protection", "Escrow payment", "Seller ratings", "Dispute resolution", "Mobile app"]
  },
  {
    slug: "spod",
    name: "SPOD",
    description: "Spreadshirt's print-on-demand service offering fast production times with European and US fulfillment.",
    headquarters: "Germany",
    founded: "2018",
    website: "spod.com",
    categories: ["apparel", "accessories"],
    shippingTime: "48-hour production guarantee",
    minOrder: "No minimum",
    pricing: "Free, pay per product",
    platforms: ["Shopify", "WooCommerce", "Squarespace", "API"],
    pros: ["48-hour production", "Consistent quality", "EU+US fulfillment", "Competitive pricing"],
    cons: ["Limited product range", "Apparel focused", "Basic customization"],
    bestFor: "POD sellers needing fastest production times",
    rating: 4.4,
    features: ["48hr production", "20M+ designs", "Express shipping", "Clip art library", "Design tool"]
  },
  {
    slug: "gelato",
    name: "Gelato",
    description: "Global print-on-demand network with local production in 32 countries for reduced shipping times and costs.",
    headquarters: "Norway",
    founded: "2007",
    website: "gelato.com",
    categories: ["apparel", "wall art", "photo products", "stationery"],
    shippingTime: "2-5 days (local production)",
    minOrder: "No minimum",
    pricing: "Free plan, Gelato+ $14.99/mo",
    platforms: ["Shopify", "Etsy", "WooCommerce", "API"],
    pros: ["32-country network", "Eco-friendly", "Local production", "Reduced shipping"],
    cons: ["Product range growing", "Quality varies by location", "Premium pricing"],
    bestFor: "Global POD brands wanting local production and eco-friendly options",
    rating: 4.3,
    features: ["Local production", "Carbon neutral", "GelatoConnect API", "Multi-currency", "Sustainability"]
  },
  {
    slug: "temu",
    name: "Temu",
    description: "Fast-growing Chinese marketplace offering ultra-low prices with improving shipping times to Western markets.",
    headquarters: "China",
    founded: "2022",
    website: "temu.com",
    categories: ["fashion", "home", "electronics", "beauty", "toys"],
    shippingTime: "7-15 days",
    minOrder: "No minimum",
    pricing: "Ultra-low prices",
    platforms: ["Direct ordering"],
    pros: ["Extremely low prices", "Wide selection", "Free shipping", "Buyer protection"],
    cons: ["Quality concerns", "No dropship automation", "Shipping times"],
    bestFor: "Budget-conscious sellers looking for low-cost product sourcing",
    rating: 3.8,
    features: ["Free shipping", "Price match", "Easy returns", "Mobile app", "Daily deals"]
  },
  {
    slug: "worldwide-brands",
    name: "Worldwide Brands",
    description: "Certified wholesale and dropship supplier directory with 16M+ products from verified suppliers.",
    headquarters: "United States",
    founded: "1999",
    website: "worldwidebrands.com",
    categories: ["general", "all categories"],
    shippingTime: "Varies by supplier",
    minOrder: "Varies by supplier",
    pricing: "$199 one-time fee",
    platforms: ["All platforms"],
    pros: ["Lifetime access", "16M+ products", "Certified suppliers", "Market research"],
    cons: ["One-time fee", "Directory model", "Self-sourcing required"],
    bestFor: "Serious entrepreneurs wanting lifetime access to verified suppliers",
    rating: 4.1,
    features: ["Certified directory", "Lifetime access", "Market research", "Light bulk suppliers", "Dropship suppliers"]
  },
  {
    slug: "autods",
    name: "AutoDS",
    description: "All-in-one dropshipping automation platform with AI store builder, product finding, and fulfillment tools.",
    headquarters: "Israel",
    founded: "2016",
    website: "autods.com",
    categories: ["general", "all supplier sources"],
    shippingTime: "Depends on supplier",
    minOrder: "No minimum",
    pricing: "From $26.90/mo",
    platforms: ["Shopify", "WooCommerce", "eBay", "Facebook", "Wix"],
    pros: ["AI store builder", "Multi-supplier", "Full automation", "Product finder", "Price monitoring"],
    cons: ["Monthly subscription", "Learning curve", "Supplier fees extra"],
    bestFor: "Dropshippers wanting complete automation across multiple suppliers",
    rating: 4.5,
    features: ["AI store builder", "Product importer", "Auto fulfillment", "Price optimizer", "Stock monitoring"]
  },
  {
    slug: "sunrise-wholesale",
    name: "Sunrise Wholesale",
    description: "US wholesale distributor offering dropshipping with 30,000+ brand-name products and same-day shipping.",
    headquarters: "United States",
    founded: "1999",
    website: "sunrisewholesalemerchandise.com",
    categories: ["electronics", "home", "garden", "toys", "fitness"],
    shippingTime: "1-3 days (US)",
    minOrder: "No minimum for dropship",
    pricing: "$49/mo membership",
    platforms: ["Amazon", "eBay", "Shopify"],
    pros: ["Brand-name products", "Same-day shipping", "US warehouse", "No restocking fees"],
    cons: ["Membership required", "Limited categories", "US only"],
    bestFor: "US sellers wanting brand-name products with fast shipping",
    rating: 4.0,
    features: ["Same-day shipping", "Brand products", "eBay/Amazon integration", "No restocking", "Free returns"]
  },
  {
    slug: "megagoods",
    name: "MegaGoods",
    description: "Consumer electronics dropshipper specializing in affordable tech products with US-based fulfillment.",
    headquarters: "United States",
    founded: "2004",
    website: "megagoods.com",
    categories: ["electronics", "gadgets", "accessories"],
    shippingTime: "1-3 days (US)",
    minOrder: "No minimum",
    pricing: "$14.99/mo",
    platforms: ["All platforms"],
    pros: ["Electronics specialist", "Fast US shipping", "Affordable membership", "Blind dropship"],
    cons: ["Limited to electronics", "Smaller catalog", "Basic platform"],
    bestFor: "Electronics-focused stores wanting US-based dropshipping",
    rating: 4.0,
    features: ["Electronics focus", "Blind shipping", "Real-time inventory", "Low membership", "US fulfillment"]
  },
  {
    slug: "brandsgateway",
    name: "BrandsGateway",
    description: "Luxury fashion dropshipping platform offering designer brands at wholesale prices with global shipping.",
    headquarters: "Lithuania",
    founded: "2017",
    website: "brandsgateway.com",
    categories: ["luxury fashion", "designer brands", "accessories"],
    shippingTime: "3-7 days (Europe), 7-14 days (US)",
    minOrder: "No minimum",
    pricing: "From €295/mo",
    platforms: ["Shopify", "WooCommerce", "Magento"],
    pros: ["Authentic luxury brands", "High margins", "Quality guaranteed", "Pre-made product content"],
    cons: ["High subscription cost", "Fashion niche only", "Luxury focus"],
    bestFor: "Luxury fashion boutiques wanting authentic designer products",
    rating: 4.2,
    features: ["Luxury brands", "Authenticity guarantee", "Content provided", "High margins", "Returns handled"]
  },
  {
    slug: "eprolo",
    name: "Eprolo",
    description: "Free dropshipping platform with branding services, warehousing, and global fulfillment network.",
    headquarters: "China",
    founded: "2015",
    website: "eprolo.com",
    categories: ["fashion", "accessories", "home", "electronics", "beauty"],
    shippingTime: "7-15 days",
    minOrder: "No minimum",
    pricing: "Free, pay per order",
    platforms: ["Shopify", "WooCommerce", "eBay"],
    pros: ["Free to use", "Branding services", "Warehousing", "POD available", "Bulk discounts"],
    cons: ["Shipping times", "Quality varies", "Limited support"],
    bestFor: "Budget dropshippers wanting branding without monthly fees",
    rating: 4.1,
    features: ["Free platform", "Custom branding", "Warehousing", "POD services", "Bulk orders"]
  },
  {
    slug: "trendsi",
    name: "Trendsi",
    description: "Women's fashion dropshipping platform with US-based fulfillment and no upfront inventory costs.",
    headquarters: "United States",
    founded: "2020",
    website: "trendsi.com",
    categories: ["women's fashion", "clothing", "accessories"],
    shippingTime: "2-5 days (US)",
    minOrder: "No minimum",
    pricing: "Free, pay per order",
    platforms: ["Shopify", "WooCommerce"],
    pros: ["US fulfillment", "No upfront cost", "Trendy styles", "Fast shipping", "Quality focused"],
    cons: ["Women's fashion only", "Limited categories", "US focused"],
    bestFor: "Women's fashion boutiques wanting fast US shipping",
    rating: 4.6,
    features: ["US warehouse", "Trend forecasting", "No inventory risk", "Quality photos", "Size guides"]
  },
  {
    slug: "faire",
    name: "Faire",
    description: "Wholesale marketplace connecting retailers with independent brands, offering net-60 payment terms.",
    headquarters: "United States",
    founded: "2017",
    website: "faire.com",
    categories: ["home", "beauty", "food", "jewelry", "apparel"],
    shippingTime: "3-7 days",
    minOrder: "Brand-specific MOQs",
    pricing: "Wholesale prices, net-60 terms",
    platforms: ["Direct ordering, some Shopify integration"],
    pros: ["Net-60 payment", "Free returns", "Independent brands", "Curated selection"],
    cons: ["MOQs required", "Not pure dropship", "Inventory needed"],
    bestFor: "Boutique retailers wanting unique products with flexible payment",
    rating: 4.5,
    features: ["Net-60 terms", "Free returns", "Brand discovery", "Reorder alerts", "Mobile app"]
  },
  {
    slug: "avasam",
    name: "Avasam",
    description: "UK-based dropshipping automation platform with UK/EU suppliers for faster European delivery.",
    headquarters: "United Kingdom",
    founded: "2018",
    website: "avasam.com",
    categories: ["general", "electronics", "home", "fashion", "toys"],
    shippingTime: "1-5 days (UK/EU)",
    minOrder: "No minimum",
    pricing: "From £20/mo",
    platforms: ["Shopify", "WooCommerce", "eBay", "Amazon"],
    pros: ["UK/EU suppliers", "Fast delivery", "Automation", "Quality vetting"],
    cons: ["UK/EU focused", "Smaller catalog", "Monthly fees"],
    bestFor: "UK and European sellers wanting local suppliers",
    rating: 4.2,
    features: ["UK fulfillment", "Multi-channel", "Auto repricing", "Inventory sync", "Returns management"]
  },
  {
    slug: "sup-dropshipping",
    name: "Sup Dropshipping",
    description: "Full-service dropshipping agent offering sourcing, quality control, and global warehousing.",
    headquarters: "China",
    founded: "2010",
    website: "supdropshipping.com",
    categories: ["general", "electronics", "fashion", "home", "outdoor"],
    shippingTime: "5-12 days (with US warehouse)",
    minOrder: "No minimum",
    pricing: "Free, service fees apply",
    platforms: ["Shopify", "WooCommerce", "eBay"],
    pros: ["Personal agent", "Quality inspection", "Private labeling", "Warehousing", "Negotiation"],
    cons: ["Service fees", "Communication delays", "Learning curve"],
    bestFor: "Sellers wanting personalized sourcing and quality control",
    rating: 4.3,
    features: ["Sourcing agent", "QC photos", "Private label", "Warehousing", "Custom packaging"]
  },
  {
    slug: "yakkyofy",
    name: "Yakkyofy",
    description: "B2B dropshipping platform with proprietary sourcing technology and automated fulfillment system.",
    headquarters: "Italy",
    founded: "2019",
    website: "yakkyofy.com",
    categories: ["general", "electronics", "fashion", "home", "sports"],
    shippingTime: "7-15 days",
    minOrder: "No minimum",
    pricing: "Free plan, Premium $29/mo",
    platforms: ["Shopify", "WooCommerce"],
    pros: ["Real-time quotes", "Virtual warehouse", "Branding options", "Multi-store"],
    cons: ["European company", "Newer platform", "Limited integrations"],
    bestFor: "European sellers wanting automated sourcing with branding",
    rating: 4.1,
    features: ["Instant quoting", "Virtual warehouse", "Branding", "Bundle creator", "Chrome extension"]
  },
];

export const getSupplierBySlug = (slug: string): Supplier | undefined => {
  return suppliers.find((s) => s.slug === slug);
};

export const getAllSuppliers = (): Supplier[] => {
  return suppliers;
};

export const getSuppliersByCategory = (category: string): Supplier[] => {
  return suppliers.filter(
    (s) => s.categories.includes(category) || s.categories.includes("general") || s.categories.includes("all categories")
  );
};

export const getSuppliersByPlatform = (platform: string): Supplier[] => {
  return suppliers.filter((s) =>
    s.platforms.some((p) => p.toLowerCase().includes(platform.toLowerCase()))
  );
};
