client_id = "0ebee2c63ba64b2e454e23a5c420fbe8"
application_url = "https://armani-histologic-sheilah.ngrok-free.dev"
embedded = false
name = "Dropwiz"

[access_scopes]
scopes = "read_products,write_products,read_publications,write_publications,read_orders,read_customers,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://www.dropwiz.ai/api/shopify/callback",
  "https://dropwiz.ai/api/shopify/callback",
  "https://armani-histologic-sheilah.ngrok-free.dev/api/shopify/callback",
  "http://localhost:3000/api/shopify/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/api/shopify/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app_subscriptions/update"]
  uri = "/api/shopify/webhooks/subscriptions-update"

  [[webhooks.subscriptions]]
  compliance_topics = [
    "customers/data_request",
    "customers/redact",
    "shop/redact",
  ]
  uri = "/api/shopify/webhooks/gdpr/dispatch"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
