import type { Store } from "@/db/schema";
import { renderStoreToHtml } from "./theme-render";

export type ThemeFile = {
  key: string;
  value: string;
};

export function buildThemeFiles(store: Store): ThemeFile[] {
  const { body, css } = renderStoreToHtml(store);

  const sectionLiquid = `{%- comment -%} Auto-generated by Dropwiz. Do not edit by hand — re-publish from Dropwiz to update. {%- endcomment -%}
{{ 'dropwiz-store.css' | asset_url | stylesheet_tag }}
<div class="dw-store" data-dropwiz-store="${store.id}">
${body}
</div>
{% schema %}
{
  "name": "Dropwiz store",
  "settings": [],
  "presets": [{ "name": "Dropwiz store" }]
}
{% endschema %}`;

  const productTemplate = JSON.stringify(
    {
      sections: {
        "dropwiz-store": { type: "dropwiz-store", settings: {} },
      },
      order: ["dropwiz-store"],
    },
    null,
    2,
  );

  return [
    { key: "sections/dropwiz-store.liquid", value: sectionLiquid },
    { key: "templates/product.dropwiz.json", value: productTemplate },
    { key: "assets/dropwiz-store.css", value: css },
  ];
}
