import type { RouterOutputs } from "@/utils/api";

export type OnboardingSource = "supplier" | "competitor" | "shopify" | "ai";

export type OnboardingStep = "source" | "details" | "customize" | "building" | "complete";

export type ScrapedProduct = RouterOutputs["scrape"]["preview"];

export type OnboardingData = {
  source: OnboardingSource | null;
  url: string;
  aiPrompt: string;
  country: string;
  currency: string;
  targetAudience: string;
  targetLanguage: string;
  scrapedProduct: ScrapedProduct | null;
};

export const ONBOARDING_STORAGE_KEY = "dropwiz_onboarding";

export const COUNTRIES = [
  { code: "US", label: "United States" },
  { code: "GB", label: "United Kingdom" },
  { code: "CA", label: "Canada" },
  { code: "AU", label: "Australia" },
  { code: "DE", label: "Germany" },
  { code: "FR", label: "France" },
  { code: "IN", label: "India" },
  { code: "BR", label: "Brazil" },
  { code: "MX", label: "Mexico" },
  { code: "JP", label: "Japan" },
  { code: "CN", label: "China" },
  { code: "KR", label: "South Korea" },
  { code: "IT", label: "Italy" },
  { code: "ES", label: "Spain" },
  { code: "NL", label: "Netherlands" },
  { code: "SE", label: "Sweden" },
  { code: "NO", label: "Norway" },
  { code: "DK", label: "Denmark" },
  { code: "FI", label: "Finland" },
  { code: "PL", label: "Poland" },
  { code: "CH", label: "Switzerland" },
  { code: "AT", label: "Austria" },
  { code: "BE", label: "Belgium" },
  { code: "IE", label: "Ireland" },
  { code: "PT", label: "Portugal" },
  { code: "NZ", label: "New Zealand" },
  { code: "SG", label: "Singapore" },
  { code: "HK", label: "Hong Kong" },
  { code: "TW", label: "Taiwan" },
  { code: "TH", label: "Thailand" },
  { code: "MY", label: "Malaysia" },
  { code: "PH", label: "Philippines" },
  { code: "ID", label: "Indonesia" },
  { code: "VN", label: "Vietnam" },
  { code: "AE", label: "United Arab Emirates" },
  { code: "SA", label: "Saudi Arabia" },
  { code: "IL", label: "Israel" },
  { code: "TR", label: "Turkey" },
  { code: "RU", label: "Russia" },
  { code: "ZA", label: "South Africa" },
  { code: "EG", label: "Egypt" },
  { code: "NG", label: "Nigeria" },
  { code: "KE", label: "Kenya" },
  { code: "AR", label: "Argentina" },
  { code: "CL", label: "Chile" },
  { code: "CO", label: "Colombia" },
  { code: "PE", label: "Peru" },
  { code: "CZ", label: "Czech Republic" },
  { code: "HU", label: "Hungary" },
  { code: "RO", label: "Romania" },
  { code: "GR", label: "Greece" },
  { code: "UA", label: "Ukraine" },
  { code: "PK", label: "Pakistan" },
  { code: "BD", label: "Bangladesh" },
  { code: "OTHER", label: "Other (specify)" },
];

export const CURRENCIES = [
  { code: "USD", label: "USD ($)" },
  { code: "EUR", label: "EUR (€)" },
  { code: "GBP", label: "GBP (£)" },
  { code: "CAD", label: "CAD (C$)" },
  { code: "AUD", label: "AUD (A$)" },
  { code: "INR", label: "INR (₹)" },
  { code: "JPY", label: "JPY (¥)" },
  { code: "CNY", label: "CNY (¥)" },
  { code: "KRW", label: "KRW (₩)" },
  { code: "BRL", label: "BRL (R$)" },
  { code: "MXN", label: "MXN ($)" },
  { code: "CHF", label: "CHF (Fr)" },
  { code: "SEK", label: "SEK (kr)" },
  { code: "NOK", label: "NOK (kr)" },
  { code: "DKK", label: "DKK (kr)" },
  { code: "PLN", label: "PLN (zł)" },
  { code: "RUB", label: "RUB (₽)" },
  { code: "TRY", label: "TRY (₺)" },
  { code: "ZAR", label: "ZAR (R)" },
  { code: "SGD", label: "SGD (S$)" },
  { code: "HKD", label: "HKD (HK$)" },
  { code: "TWD", label: "TWD (NT$)" },
  { code: "THB", label: "THB (฿)" },
  { code: "MYR", label: "MYR (RM)" },
  { code: "PHP", label: "PHP (₱)" },
  { code: "IDR", label: "IDR (Rp)" },
  { code: "VND", label: "VND (₫)" },
  { code: "AED", label: "AED (د.إ)" },
  { code: "SAR", label: "SAR (﷼)" },
  { code: "ILS", label: "ILS (₪)" },
  { code: "EGP", label: "EGP (E£)" },
  { code: "NGN", label: "NGN (₦)" },
  { code: "KES", label: "KES (KSh)" },
  { code: "ARS", label: "ARS ($)" },
  { code: "CLP", label: "CLP ($)" },
  { code: "COP", label: "COP ($)" },
  { code: "PEN", label: "PEN (S/)" },
  { code: "CZK", label: "CZK (Kč)" },
  { code: "HUF", label: "HUF (Ft)" },
  { code: "RON", label: "RON (lei)" },
  { code: "BGN", label: "BGN (лв)" },
  { code: "HRK", label: "HRK (kn)" },
  { code: "ISK", label: "ISK (kr)" },
  { code: "NZD", label: "NZD (NZ$)" },
  { code: "PKR", label: "PKR (₨)" },
  { code: "BDT", label: "BDT (৳)" },
  { code: "UAH", label: "UAH (₴)" },
  { code: "QAR", label: "QAR (﷼)" },
  { code: "KWD", label: "KWD (د.ك)" },
  { code: "BHD", label: "BHD (ب.د)" },
  { code: "OTHER", label: "Other (specify)" },
];

export const TARGET_AUDIENCES = [
  { id: "general", label: "General consumers" },
  { id: "premium", label: "Premium buyers" },
  { id: "budget", label: "Budget-conscious" },
  { id: "tech", label: "Tech enthusiasts" },
  { id: "parents", label: "Parents & families" },
  { id: "fitness", label: "Health & fitness" },
  { id: "beauty", label: "Beauty & skincare" },
  { id: "fashion", label: "Fashion forward" },
  { id: "gamers", label: "Gamers" },
  { id: "professionals", label: "Business professionals" },
  { id: "students", label: "Students" },
  { id: "seniors", label: "Seniors" },
  { id: "outdoor", label: "Outdoor enthusiasts" },
  { id: "pet", label: "Pet owners" },
  { id: "eco", label: "Eco-conscious" },
];

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "es", label: "Spanish (Español)" },
  { code: "fr", label: "French (Français)" },
  { code: "de", label: "German (Deutsch)" },
  { code: "it", label: "Italian (Italiano)" },
  { code: "pt", label: "Portuguese (Português)" },
  { code: "pt-BR", label: "Portuguese - Brazil" },
  { code: "nl", label: "Dutch (Nederlands)" },
  { code: "pl", label: "Polish (Polski)" },
  { code: "ru", label: "Russian (Русский)" },
  { code: "uk", label: "Ukrainian (Українська)" },
  { code: "cs", label: "Czech (Čeština)" },
  { code: "sk", label: "Slovak (Slovenčina)" },
  { code: "hu", label: "Hungarian (Magyar)" },
  { code: "ro", label: "Romanian (Română)" },
  { code: "bg", label: "Bulgarian (Български)" },
  { code: "hr", label: "Croatian (Hrvatski)" },
  { code: "sr", label: "Serbian (Српски)" },
  { code: "sl", label: "Slovenian (Slovenščina)" },
  { code: "el", label: "Greek (Ελληνικά)" },
  { code: "tr", label: "Turkish (Türkçe)" },
  { code: "ar", label: "Arabic (العربية)" },
  { code: "he", label: "Hebrew (עברית)" },
  { code: "fa", label: "Persian (فارسی)" },
  { code: "hi", label: "Hindi (हिन्दी)" },
  { code: "bn", label: "Bengali (বাংলা)" },
  { code: "ta", label: "Tamil (தமிழ்)" },
  { code: "te", label: "Telugu (తెలుగు)" },
  { code: "mr", label: "Marathi (मराठी)" },
  { code: "gu", label: "Gujarati (ગુજરાતી)" },
  { code: "kn", label: "Kannada (ಕನ್ನಡ)" },
  { code: "ml", label: "Malayalam (മലയാളം)" },
  { code: "pa", label: "Punjabi (ਪੰਜਾਬੀ)" },
  { code: "ur", label: "Urdu (اردو)" },
  { code: "zh-CN", label: "Chinese - Simplified (简体中文)" },
  { code: "zh-TW", label: "Chinese - Traditional (繁體中文)" },
  { code: "ja", label: "Japanese (日本語)" },
  { code: "ko", label: "Korean (한국어)" },
  { code: "th", label: "Thai (ไทย)" },
  { code: "vi", label: "Vietnamese (Tiếng Việt)" },
  { code: "id", label: "Indonesian (Bahasa Indonesia)" },
  { code: "ms", label: "Malay (Bahasa Melayu)" },
  { code: "tl", label: "Filipino (Tagalog)" },
  { code: "sv", label: "Swedish (Svenska)" },
  { code: "no", label: "Norwegian (Norsk)" },
  { code: "da", label: "Danish (Dansk)" },
  { code: "fi", label: "Finnish (Suomi)" },
  { code: "is", label: "Icelandic (Íslenska)" },
  { code: "et", label: "Estonian (Eesti)" },
  { code: "lv", label: "Latvian (Latviešu)" },
  { code: "lt", label: "Lithuanian (Lietuvių)" },
  { code: "sw", label: "Swahili (Kiswahili)" },
  { code: "af", label: "Afrikaans" },
  { code: "OTHER", label: "Other (specify)" },
];

export const defaultOnboardingData: OnboardingData = {
  source: null,
  url: "",
  aiPrompt: "",
  country: "US",
  currency: "USD",
  targetAudience: "general",
  targetLanguage: "en",
  scrapedProduct: null,
};
